-- ============================================================
-- Facility Bed/Capacity Tracking — RETIRED (SPEC-STATUS.md B19, 2026-08-21)
-- ============================================================
--
-- This file used to CREATE + seed `newui_facility_capacity`. That table
-- was never read or written by any API endpoint or page — the live
-- capacity model is a different pair, `capacity_categories` +
-- `facility_capacity` (sql/run_facility_capacity_tables.php,
-- api/facility-capacity.php). `newui_facility_capacity` was absent from
-- sql/schema_manifest.json, confirming it was genuinely outside the
-- tracked-writer set: a decoy a future developer could easily mistake for
-- the real capacity model.
--
-- The only place that ever looked at `newui_facility_capacity` was
-- facility-board.php, and only to check the table's EXISTENCE (never its
-- data) as a proxy for "is capacity tracking available" — which was
-- itself checking the wrong table's existence to gate loading data from
-- the RIGHT one. Fixed in the same change (facility-board.php now checks
-- `facility_capacity`, the table its own capacity fetch actually reads).
--
-- Existing installs: sql/run_facility_capacity_legacy_table_drop.php drops
-- the table, but only after confirming every row still matches the exact
-- auto-seeded placeholder shape this file used to INSERT
-- (category='General', total=0, occupied=0, status='open') — never a
-- blind drop. This file is kept (rather than removed from
-- tools/install_fresh.php's foundational-imports list) as a no-op so its
-- filename and this history stay easy to find.
--
-- This file intentionally creates nothing on a fresh install going
-- forward. Do not re-add the CREATE TABLE below without re-reading the
-- B19 writeup in specs/SPEC-STATUS.md first.
