<?php
/**
 * NewUI v4.0 API — Map Image Overlays (Phase 110 / GH #43)
 *
 * Special-event map image overlays: upload a venue map (JPG/PNG, or PDF
 * page 1 converted server-side), geo-anchor it with three corner points,
 * and every Leaflet map that uses MapPrefs can toggle it from the layer
 * control — above base tiles, below markups and markers.
 *
 * GET  /api/map-image-overlays.php      — List overlays (any authenticated user)
 *
 * POST endpoints (CSRF + action.manage_map_overlays required):
 *   POST multipart action=create  — Upload a new overlay image (fields: name, file, csrf_token)
 *   POST JSON      action=update  — Update name / anchors / opacity / enabled
 *   POST JSON      action=delete  — Delete row + stored file
 *
 * SECURITY (mirrors the F-001-hardened api/upload.php approach):
 *   - MIME derived from finfo_file() on the temp file (never $_FILES['type']).
 *   - Extension allowlist: jpg/jpeg/png/pdf only. Stored filename is random
 *     hex + canonical extension — the user-supplied name is discarded.
 *   - 100 MB size cap (server PHP ini may cap lower).
 *   - PDFs converted to PNG server-side (Imagick, else ghostscript); the
 *     PDF itself is never stored.
 *   - Delete path realpath-checked to stay inside uploads/overlays/.
 */

ini_set('display_errors', '0');
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../inc/rbac.php';
require_once __DIR__ . '/../inc/audit.php';

$prefix     = $GLOBALS['db_prefix'] ?? '';
$uploadDir  = __DIR__ . '/../uploads';
$overlayDir = $uploadDir . '/overlays';

// ── Allowlist: extension → expected MIME(s). Overlays accept images + PDF only.
$OVERLAY_EXT_MIME = [
    'png'  => ['image/png'],
    'jpg'  => ['image/jpeg'],
    'jpeg' => ['image/jpeg'],
    'pdf'  => ['application/pdf'],
];
$OVERLAY_MIME_TO_EXT = [
    'image/png'       => 'png',
    'image/jpeg'      => 'jpg',
    'application/pdf' => 'pdf',
];
$OVERLAY_MAX_BYTES = 100 * 1048576; // 100 MB cap (a beta tester GH #43 — event PDFs can be large). NOTE: PHP upload_max_filesize + post_max_size must also allow this.

// ── Ensure table exists (defensive — migration is sql/run_map_image_overlays.php)
try {
    db_query("CREATE TABLE IF NOT EXISTS `{$prefix}map_image_overlays` (
        `id`          INT NOT NULL AUTO_INCREMENT,
        `name`        VARCHAR(128) NOT NULL,
        `file_path`   VARCHAR(255) NOT NULL,
        `mime`        VARCHAR(64)  NOT NULL,
        `anchor_json` TEXT DEFAULT NULL,
        `opacity`     DECIMAL(3,2) DEFAULT 0.70,
        `enabled`     TINYINT(1)   DEFAULT 1,
        `sort_order`  INT          DEFAULT 0,
        `created_by`  INT          DEFAULT NULL,
        `created_at`  DATETIME     DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`),
        KEY `idx_enabled` (`enabled`),
        KEY `idx_sort`    (`sort_order`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
} catch (Exception $e) { /* table create is best-effort here */ }

/**
 * Ensure uploads/overlays exists with the anti-execution .htaccess in the
 * uploads root (same defense-in-depth as api/upload.php).
 */
function overlay_ensure_dir(string $uploadDir, string $overlayDir): bool {
    if (!is_dir($uploadDir)) {
        @mkdir($uploadDir, 0755, true);
    }
    $htaccess = $uploadDir . '/.htaccess';
    if (!file_exists($htaccess)) {
        @file_put_contents($htaccess, "# Auto-generated by upload.php — do not remove\n"
            . "<IfModule mod_php.c>\n"
            . "    php_flag engine off\n"
            . "</IfModule>\n"
            . "<FilesMatch \"\\.(php|phar|phtml|pht|phtm|inc|htaccess|html|htm|svg|xml|xsl|vbs|js)$\">\n"
            . "    Require all denied\n"
            . "</FilesMatch>\n"
            . "Options -ExecCGI\n");
    }
    if (!is_dir($overlayDir)) {
        @mkdir($overlayDir, 0755, true);
    }
    return is_dir($overlayDir) && is_writable($overlayDir);
}

/**
 * Convert page 1 of a PDF to a PNG. Imagick if available, else a
 * ghostscript shell-out. Returns true when $destPath holds a non-empty PNG.
 */
function overlay_pdf_to_png(string $srcPath, string $destPath): bool {
    // Preferred: Imagick (no shell involved)
    if (class_exists('Imagick')) {
        try {
            // Security review 2026-07-04 (LOW): cap memory + rasterized
            // pixels so a ~1 MB PDF declaring a giant MediaBox can't
            // rasterize into a multi-gigapixel PNG and exhaust the box.
            // Only a privileged user can reach here, but bound it anyway.
            if (defined('Imagick::RESOURCETYPE_MEMORY')) {
                @Imagick::setResourceLimit(Imagick::RESOURCETYPE_MEMORY, 256 * 1024 * 1024);
                @Imagick::setResourceLimit(Imagick::RESOURCETYPE_MAP, 512 * 1024 * 1024);
            }
            $im = new Imagick();
            $im->setResolution(150, 150);
            $im->readImage($srcPath . '[0]'); // first page only (v1)
            // Reject decompression bombs: > ~50 megapixels after raster.
            $w = (int) $im->getImageWidth();
            $h = (int) $im->getImageHeight();
            if ($w * $h > 50000000) {
                $im->clear();
                error_log('[map-image-overlays] PDF rasterized too large (' . $w . 'x' . $h . '), rejected');
                @unlink($destPath);
                return false;
            }
            $im->setImageBackgroundColor('white');
            $im->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
            $im->setImageFormat('png');
            $im->writeImage($destPath);
            $im->clear();
            if (is_file($destPath) && filesize($destPath) > 0) {
                return true;
            }
        } catch (Exception $e) {
            error_log('[map-image-overlays] Imagick PDF conversion failed: ' . $e->getMessage());
            @unlink($destPath);
        }
    }
    // Fallback: ghostscript. All paths escapeshellarg'd; no user input in
    // the command beyond the (already random-named / tmp) file paths.
    if (function_exists('shell_exec')) {
        foreach (['gs', 'gswin64c', 'gswin32c'] as $bin) {
            // -dMaxBitmap bounds the rasterizer's memory (security
            // review 2026-07-04) so an oversized PDF can't blow up gs.
            $cmd = $bin
                 . ' -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r150'
                 . ' -dMaxBitmap=200000000'
                 . ' -dFirstPage=1 -dLastPage=1'
                 . ' -sOutputFile=' . escapeshellarg($destPath)
                 . ' ' . escapeshellarg($srcPath) . ' 2>&1';
            @shell_exec($cmd);
            if (is_file($destPath) && filesize($destPath) > 0) {
                return true;
            }
            @unlink($destPath);
        }
    }
    return false;
}

/**
 * Validate + sanitize an anchors structure:
 *   {tl:{lat,lng}, tr:{lat,lng}, bl:{lat,lng}}
 * Returns a clean float-typed array, or null when invalid.
 */
function overlay_clean_anchors($raw): ?array {
    if (!is_array($raw)) return null;
    $clean = [];
    foreach (['tl', 'tr', 'bl'] as $corner) {
        if (!isset($raw[$corner]) || !is_array($raw[$corner])) return null;
        $lat = $raw[$corner]['lat'] ?? null;
        $lng = $raw[$corner]['lng'] ?? null;
        if (!is_numeric($lat) || !is_numeric($lng)) return null;
        $lat = (float) $lat;
        $lng = (float) $lng;
        if ($lat < -90 || $lat > 90 || $lng < -180 || $lng > 180) return null;
        $clean[$corner] = ['lat' => $lat, 'lng' => $lng];
    }
    return $clean;
}

/** Shape a DB row for JSON output. */
function overlay_row_out(array $row): array {
    $anchors = null;
    if (!empty($row['anchor_json'])) {
        $decoded = json_decode($row['anchor_json'], true);
        if (is_array($decoded)) $anchors = $decoded;
    }
    return [
        'id'         => (int) $row['id'],
        'name'       => $row['name'],
        'url'        => 'uploads/overlays/' . basename($row['file_path']),
        'anchors'    => $anchors,
        'opacity'    => (float) $row['opacity'],
        'enabled'    => (int) $row['enabled'],
        'sort_order' => (int) $row['sort_order'],
        'mime'       => $row['mime'],
        'created_at' => $row['created_at'],
    ];
}

/** Mutation gate: RBAC permission (with legacy admin fallback, as api/routing.php). */
function overlay_require_manage(): void {
    if (function_exists('rbac_can') && !rbac_can('action.manage_map_overlays')) {
        if (!is_admin()) {
            json_error('Insufficient permissions', 403);
        }
    }
}

// ── GET: list overlays (any authenticated user) ─────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    try {
        $rows = db_fetch_all(
            "SELECT * FROM `{$prefix}map_image_overlays`
             ORDER BY sort_order ASC, id ASC"
        );
        $out = [];
        foreach ($rows as $row) {
            $out[] = overlay_row_out($row);
        }
        json_response(['overlays' => $out]);
    } catch (Exception $e) {
        json_error_safe('Failed to load overlays', $e, 'map-image-overlays');
    }
}

// ── POST: create / update / delete ───────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Multipart upload (action=create) vs JSON body (update/delete)
    $isMultipart = isset($_FILES['file']) || (($_POST['action'] ?? '') === 'create');

    if ($isMultipart) {
        $action = $_POST['action'] ?? '';
        $token  = $_POST['csrf_token'] ?? '';
    } else {
        $input = json_decode(file_get_contents('php://input'), true);
        if (!$input) {
            $input = $_POST;
        }
        $action = $input['action'] ?? '';
        $token  = $input['csrf_token'] ?? '';
    }

    if (!csrf_verify($token)) {
        json_error('Invalid CSRF token', 403);
    }
    overlay_require_manage();

    // Guard: a multipart POST that isn't create still reaches the JSON
    // branches below — make sure $input is always an array.
    if (!isset($input) || !is_array($input)) {
        $input = $_POST;
    }

    // ── action=create: multipart image/PDF upload ────────────────────────
    if ($action === 'create') {
        if (empty($_FILES['file'])) {
            json_error('No file uploaded');
        }
        $file = $_FILES['file'];

        if ($file['error'] !== UPLOAD_ERR_OK) {
            $errors = [
                UPLOAD_ERR_INI_SIZE   => 'File exceeds PHP upload_max_filesize',
                UPLOAD_ERR_FORM_SIZE  => 'File exceeds form MAX_FILE_SIZE',
                UPLOAD_ERR_PARTIAL    => 'File was only partially uploaded',
                UPLOAD_ERR_NO_FILE    => 'No file was uploaded',
                UPLOAD_ERR_NO_TMP_DIR => 'Missing temp directory',
                UPLOAD_ERR_CANT_WRITE => 'Failed to write to disk',
            ];
            json_error($errors[$file['error']] ?? 'Upload error code ' . $file['error']);
        }
        if (!is_uploaded_file($file['tmp_name'])) {
            json_error('Invalid upload');
        }
        if ($file['size'] > $OVERLAY_MAX_BYTES) {
            json_error('File too large (' . round($file['size'] / 1048576, 1) . ' MB). Maximum: 100 MB. If a large PDF still fails, the server PHP upload_max_filesize/post_max_size limits may be lower.');
        }

        // HARDENED: derive MIME from the temp file, never trust $_FILES['type']
        $detectedMime = null;
        if (function_exists('finfo_open')) {
            $finfo = @finfo_open(FILEINFO_MIME_TYPE);
            if ($finfo) {
                $detectedMime = @finfo_file($finfo, $file['tmp_name']);
                @finfo_close($finfo);
            }
        }
        if (!$detectedMime) {
            $detectedMime = @mime_content_type($file['tmp_name']) ?: '';
        }
        $detectedMime = strtolower(trim((string) $detectedMime));
        if ($detectedMime === '') {
            json_error('Could not determine file type — refusing upload');
        }
        if (!isset($OVERLAY_MIME_TO_EXT[$detectedMime])) {
            json_error('File type not allowed: ' . $detectedMime . ' (JPG, PNG or PDF only)');
        }
        $canonicalExt = $OVERLAY_MIME_TO_EXT[$detectedMime];

        // Cross-check the user-provided extension against the detected MIME —
        // defends against polyglots masquerading as legitimate types.
        $userExt = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
        if ($userExt !== '' && isset($OVERLAY_EXT_MIME[$userExt])) {
            if (!in_array($detectedMime, $OVERLAY_EXT_MIME[$userExt], true)) {
                json_error("File extension does not match content (.{$userExt} vs {$detectedMime})");
            }
        } elseif ($userExt !== '') {
            json_error("File extension not allowed: .{$userExt} (JPG, PNG or PDF only)");
        }

        if (!overlay_ensure_dir($uploadDir, $overlayDir)) {
            json_error('Overlay upload directory is not writable', 500);
        }

        // Random filename — user-supplied name is discarded entirely.
        $base = bin2hex(random_bytes(16));

        if ($canonicalExt === 'pdf') {
            // Convert page 1 → PNG; the PDF itself is never stored.
            $safeName = $base . '.png';
            $absPath  = $overlayDir . '/' . $safeName;
            if (!overlay_pdf_to_png($file['tmp_name'], $absPath)) {
                json_error('PDF conversion not available on this server — export the map as PNG or JPG and upload that instead', 422);
            }
            $storedMime = 'image/png';
        } else {
            $safeName = $base . '.' . $canonicalExt;
            $absPath  = $overlayDir . '/' . $safeName;
            if (!move_uploaded_file($file['tmp_name'], $absPath)) {
                json_error('Failed to save file to disk', 500);
            }
            $storedMime = $detectedMime;
        }

        $name = trim((string) ($_POST['name'] ?? ''));
        if ($name === '') {
            $name = (string) pathinfo($file['name'], PATHINFO_FILENAME);
        }
        $name = substr($name, 0, 128);
        if ($name === '') {
            $name = 'Event overlay';
        }

        try {
            db_query(
                "INSERT INTO `{$prefix}map_image_overlays`
                    (name, file_path, mime, anchor_json, opacity, enabled, sort_order, created_by)
                 VALUES (?, ?, ?, NULL, 0.70, 1, 0, ?)",
                [$name, 'uploads/overlays/' . $safeName, $storedMime, (int) ($_SESSION['user_id'] ?? 0)]
            );
            $newId = (int) db_insert_id();
        } catch (Exception $e) {
            @unlink($absPath); // don't strand the file if the row failed
            json_error_safe('Failed to save overlay record', $e, 'map-image-overlays');
        }

        try {
            audit_log('config', 'image_overlay_create', 'map_image_overlays', $newId,
                'Uploaded event map overlay "' . $name . '"',
                ['file' => $safeName, 'mime' => $storedMime, 'orig_name' => $file['name'], 'size' => $file['size']]);
        } catch (Exception $e) { /* audit must never break the action */ }

        try {
            $row = db_fetch_one("SELECT * FROM `{$prefix}map_image_overlays` WHERE id = ?", [$newId]);
            json_response(['ok' => true, 'overlay' => $row ? overlay_row_out($row) : null]);
        } catch (Exception $e) {
            json_error_safe('Overlay saved but could not be re-read', $e, 'map-image-overlays');
        }
    }

    // ── action=update: name / anchors / opacity / enabled ────────────────
    if ($action === 'update') {
        $id = (int) ($input['id'] ?? 0);
        if (!$id) {
            json_error('Overlay ID is required');
        }
        try {
            $existing = db_fetch_one("SELECT * FROM `{$prefix}map_image_overlays` WHERE id = ?", [$id]);
        } catch (Exception $e) {
            json_error_safe('Failed to load overlay', $e, 'map-image-overlays');
        }
        if (!$existing) {
            json_error('Overlay not found', 404);
        }

        $sets    = [];
        $params  = [];
        $changed = [];

        if (array_key_exists('name', $input)) {
            $name = substr(trim((string) $input['name']), 0, 128);
            if ($name === '') {
                json_error('Name cannot be empty');
            }
            $sets[]   = '`name` = ?';
            $params[] = $name;
            $changed['name'] = $name;
        }
        if (array_key_exists('anchors', $input)) {
            $anchors = overlay_clean_anchors($input['anchors']);
            if ($anchors === null) {
                json_error('Invalid anchors — tl/tr/bl each need numeric lat (-90..90) and lng (-180..180)');
            }
            $sets[]   = '`anchor_json` = ?';
            $params[] = json_encode($anchors);
            $changed['anchors'] = $anchors;
        }
        if (array_key_exists('opacity', $input)) {
            if (!is_numeric($input['opacity'])) {
                json_error('Opacity must be numeric');
            }
            $opacity  = max(0.05, min(1.0, (float) $input['opacity']));
            $sets[]   = '`opacity` = ?';
            $params[] = $opacity;
            $changed['opacity'] = $opacity;
        }
        if (array_key_exists('enabled', $input)) {
            $enabled  = ((int) $input['enabled']) ? 1 : 0;
            $sets[]   = '`enabled` = ?';
            $params[] = $enabled;
            $changed['enabled'] = $enabled;
        }

        if (empty($sets)) {
            json_error('Nothing to update');
        }

        try {
            $params[] = $id;
            db_query(
                "UPDATE `{$prefix}map_image_overlays` SET " . implode(', ', $sets) . " WHERE id = ?",
                $params
            );
        } catch (Exception $e) {
            json_error_safe('Failed to update overlay', $e, 'map-image-overlays');
        }

        try {
            audit_log('config', 'image_overlay_update', 'map_image_overlays', $id,
                'Updated event map overlay "' . $existing['name'] . '"', $changed);
        } catch (Exception $e) { /* audit must never break the action */ }

        try {
            $row = db_fetch_one("SELECT * FROM `{$prefix}map_image_overlays` WHERE id = ?", [$id]);
            json_response(['ok' => true, 'overlay' => $row ? overlay_row_out($row) : null]);
        } catch (Exception $e) {
            json_error_safe('Overlay updated but could not be re-read', $e, 'map-image-overlays');
        }
    }

    // ── action=delete: remove row + stored file ───────────────────────────
    if ($action === 'delete') {
        $id = (int) ($input['id'] ?? 0);
        if (!$id) {
            json_error('Overlay ID is required');
        }
        try {
            $existing = db_fetch_one("SELECT * FROM `{$prefix}map_image_overlays` WHERE id = ?", [$id]);
        } catch (Exception $e) {
            json_error_safe('Failed to load overlay', $e, 'map-image-overlays');
        }
        if (!$existing) {
            json_error('Overlay not found', 404);
        }

        // Unlink the stored file — realpath containment check so a tampered
        // file_path can never delete anything outside uploads/overlays/.
        $abs     = $overlayDir . '/' . basename($existing['file_path']);
        $real    = realpath($abs);
        $realDir = realpath($overlayDir);
        if ($real !== false && $realDir !== false
            && strpos($real, $realDir . DIRECTORY_SEPARATOR) === 0) {
            @unlink($real);
        }

        try {
            db_query("DELETE FROM `{$prefix}map_image_overlays` WHERE id = ?", [$id]);
        } catch (Exception $e) {
            json_error_safe('Failed to delete overlay', $e, 'map-image-overlays');
        }

        try {
            audit_log('config', 'image_overlay_delete', 'map_image_overlays', $id,
                'Deleted event map overlay "' . $existing['name'] . '"',
                ['file' => basename($existing['file_path'])]);
        } catch (Exception $e) { /* audit must never break the action */ }

        json_response(['ok' => true]);
    }

    json_error('Unknown action: ' . $action);
}

json_error('Method not allowed', 405);
