<?php
/**
 * NewUI v4.0 API — File Upload
 *
 * POST /api/upload.php                — Upload file(s)            (CSRF + RBAC required)
 * GET  /api/upload.php?entity=X&id=Y  — List files for an entity  (per-entity access check)
 * GET  /api/upload.php?file_id=X      — Download a file           (per-entity access check)
 * POST action=delete                  — Delete a file             (CSRF + per-entity access check)
 * GET  /api/upload.php?disk_status=1  — Get disk usage stats
 *
 * Files are stored locally in uploads/{entity}/{entity_id}/.
 * Supported entities: incident, member, facility, equipment, vehicle, sop, general.
 *
 * SECURITY (F-001 hardening, 2026-05-04):
 *   - CSRF token verified on POST (multipart sends as form field).
 *   - MIME derived from finfo_file() on the temp file (never $_FILES['type']).
 *   - File extension is enforced via an allowlist + a derived extension
 *     keyed off the verified MIME. The user-supplied extension is discarded.
 *   - Per-entity access enforced via user_can_access_entity().
 *   - Upload directory ships with .htaccess that disables PHP execution.
 *
 * Config (settings table):
 *   upload_max_file_size   — Max per-file size in MB (default: 30)
 *   upload_disk_warn_pct   — Disk usage % to show warning (default: 70)
 *   upload_disk_block_pct  — Disk usage % to block uploads (default: 80)
 *   upload_allowed_types   — Reserved for future per-instance overrides; not
 *                            consulted by this endpoint anymore (extensions are
 *                            allowlisted in code so admin misconfiguration
 *                            cannot reintroduce the RCE primitive).
 */

ini_set('display_errors', '0');
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../inc/rbac.php';
require_once __DIR__ . '/../inc/audit.php';
require_once __DIR__ . '/../inc/access.php';

$method = $_SERVER['REQUEST_METHOD'];
$prefix = $GLOBALS['db_prefix'] ?? '';
$uploadDir = __DIR__ . '/../uploads';

// ── Allowlist: extension → expected MIME(s). Used for both uploads and
//    download Content-Type. Anything not in this list is rejected.
$ALLOWED_EXT_MIME = [
    'png'  => ['image/png'],
    'jpg'  => ['image/jpeg'],
    'jpeg' => ['image/jpeg'],
    'gif'  => ['image/gif'],
    'webp' => ['image/webp'],
    'bmp'  => ['image/bmp', 'image/x-ms-bmp'],
    'pdf'  => ['application/pdf'],
    'csv'  => ['text/csv', 'text/plain', 'application/csv'],
    'tsv'  => ['text/tab-separated-values', 'text/plain'],
    'txt'  => ['text/plain'],
    'log'  => ['text/plain'],
    'json' => ['application/json', 'text/plain'],
    'doc'  => ['application/msword'],
    'docx' => ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'],
    'xls'  => ['application/vnd.ms-excel'],
    'xlsx' => ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/zip'],
    'ppt'  => ['application/vnd.ms-powerpoint'],
    'pptx' => ['application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/zip'],
    'rtf'  => ['application/rtf', 'text/rtf'],
    'odt'  => ['application/vnd.oasis.opendocument.text'],
    'ods'  => ['application/vnd.oasis.opendocument.spreadsheet'],
    'mp3'  => ['audio/mpeg'],
    'wav'  => ['audio/wav', 'audio/x-wav'],
    'mp4'  => ['video/mp4'],
    'webm' => ['video/webm'],
];

// MIME → preferred canonical extension (used to overwrite user-supplied ext)
$MIME_TO_EXT = [];
foreach ($ALLOWED_EXT_MIME as $ext => $mimes) {
    foreach ($mimes as $m) {
        // First ext seen for a MIME wins — so png beats bmp on the bmp alt MIME, etc.
        if (!isset($MIME_TO_EXT[$m])) {
            $MIME_TO_EXT[$m] = $ext;
        }
    }
}

// Ensure uploads directory exists, and that .htaccess is present (defense-in-depth).
if (!is_dir($uploadDir)) {
    @mkdir($uploadDir, 0755, true);
}
$htaccess = $uploadDir . '/.htaccess';
if (!file_exists($htaccess)) {
    @file_put_contents($htaccess, "# Auto-generated by upload.php — do not remove\n"
        . "<IfModule mod_php.c>\n"
        . "    php_flag engine off\n"
        . "</IfModule>\n"
        . "<FilesMatch \"\\.(php|phar|phtml|pht|phtm|inc|htaccess|html|htm|svg|xml|xsl|vbs|js)$\">\n"
        . "    Require all denied\n"
        . "</FilesMatch>\n"
        . "Options -ExecCGI\n");
}

// Ensure file_uploads table exists
try {
    db_query("CREATE TABLE IF NOT EXISTS `{$prefix}file_uploads` (
        `id`          INT AUTO_INCREMENT PRIMARY KEY,
        `entity_type` VARCHAR(32)  NOT NULL COMMENT 'incident, member, facility, etc.',
        `entity_id`   INT          NOT NULL,
        `filename`    VARCHAR(255) NOT NULL,
        `orig_name`   VARCHAR(255) NOT NULL,
        `mime_type`   VARCHAR(128) NOT NULL DEFAULT 'application/octet-stream',
        `file_size`   BIGINT       NOT NULL DEFAULT 0,
        `file_path`   VARCHAR(512) NOT NULL,
        `uploaded_by` INT          NOT NULL DEFAULT 0,
        `uploaded_by_name` VARCHAR(64) NOT NULL DEFAULT '',
        `description` VARCHAR(255) DEFAULT '',
        `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
        KEY `idx_entity` (`entity_type`, `entity_id`),
        KEY `idx_uploaded_by` (`uploaded_by`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
} catch (Exception $e) {}

// ── Config helpers ──
function upload_config($key, $default) {
    global $prefix;
    try {
        // PRE-RELEASE-FIXES #12 — settings column is `name`, not `key`.
        // Pre-fix this query always failed silently and every config knob
        // (max file size, disk warn/block %) was stuck on its default.
        $val = db_fetch_value("SELECT `value` FROM `{$prefix}settings` WHERE `name` = ?", [$key]);
        return $val !== null ? $val : $default;
    } catch (Exception $e) {
        return $default;
    }
}

function disk_usage_stats() {
    global $uploadDir;
    $totalSize = 0;
    if (is_dir($uploadDir)) {
        $iter = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($uploadDir, RecursiveDirectoryIterator::SKIP_DOTS)
        );
        foreach ($iter as $file) {
            $totalSize += $file->getSize();
        }
    }
    $diskFree = @disk_free_space($uploadDir);
    $diskTotal = @disk_total_space($uploadDir);
    $usedPct = ($diskTotal > 0) ? round(($diskTotal - $diskFree) / $diskTotal * 100, 1) : 0;

    return [
        'uploads_bytes' => $totalSize,
        'uploads_mb'    => round($totalSize / 1048576, 2),
        'disk_free_mb'  => $diskFree !== false ? round($diskFree / 1048576, 0) : null,
        'disk_total_mb' => $diskTotal !== false ? round($diskTotal / 1048576, 0) : null,
        'disk_used_pct' => $usedPct
    ];
}

// ── Look up a file row by id (used by GET download + POST delete) ──
function load_file_row(int $fileId) {
    global $prefix;
    try {
        return db_fetch_one("SELECT * FROM `{$prefix}file_uploads` WHERE id = ?", [$fileId]);
    } catch (Exception $e) {
        return null;
    }
}

// ── GET ──
if ($method === 'GET') {
    // Disk status
    if (!empty($_GET['disk_status'])) {
        $stats = disk_usage_stats();
        $stats['warn_pct']  = (float) upload_config('upload_disk_warn_pct', 70);
        $stats['block_pct'] = (float) upload_config('upload_disk_block_pct', 80);
        $stats['max_file_mb'] = (float) upload_config('upload_max_file_size', 30);
        json_response($stats);
    }

    // Download a file
    if (!empty($_GET['file_id'])) {
        $fileId = intval($_GET['file_id']);
        $file = load_file_row($fileId);
        if (!$file) {
            json_error('File not found', 404);
        }

        if (!user_can_access_entity((string) $file['entity_type'], (int) $file['entity_id'])) {
            // 404 (not 403) per Constitution rule #27 — don't leak existence.
            json_error('File not found', 404);
        }

        $path = $uploadDir . '/' . $file['file_path'];
        if (!file_exists($path)) json_error('File missing from disk', 404);

        // Force a safe content type — never echo the stored MIME blindly,
        // because pre-hardening uploads may have a malicious value cached.
        $storedExt = strtolower(pathinfo($file['filename'], PATHINFO_EXTENSION));
        global $ALLOWED_EXT_MIME;
        $safeMime = isset($ALLOWED_EXT_MIME[$storedExt])
            ? $ALLOWED_EXT_MIME[$storedExt][0]
            : 'application/octet-stream';

        header('Content-Type: ' . $safeMime);
        header('Content-Length: ' . filesize($path));
        header('X-Content-Type-Options: nosniff');
        // Always attachment for unknown types; inline only for media we trust.
        $disposition = (strpos($safeMime, 'image/') === 0 || $safeMime === 'application/pdf')
            ? 'inline' : 'attachment';
        header('Content-Disposition: ' . $disposition
            . '; filename="' . basename($file['orig_name']) . '"');
        readfile($path);
        exit;
    }

    // List files for entity
    $entityType = $_GET['entity'] ?? '';
    $entityId = intval($_GET['id'] ?? 0);

    if (!$entityType) json_error('entity parameter required');

    if (!user_can_access_entity((string) $entityType, $entityId)) {
        // Empty list, not 403 — same shape so non-admins simply see nothing.
        json_response(['files' => [], 'entity' => $entityType, 'entity_id' => $entityId]);
    }

    try {
        $files = db_fetch_all(
            "SELECT * FROM `{$prefix}file_uploads`
             WHERE entity_type = ? AND entity_id = ?
             ORDER BY created_at DESC",
            [$entityType, $entityId]
        );
    } catch (Exception $e) {
        $files = [];
    }

    json_response(['files' => $files, 'entity' => $entityType, 'entity_id' => $entityId]);
}

// ── POST (upload + delete) ──
if ($method === 'POST') {
    if (!rbac_can('action.upload_files')) {
        json_error('Insufficient permissions: upload files', 403);
    }

    // CSRF — multipart uploads carry it as a form field; JSON bodies in body
    $csrfToken = $_POST['csrf_token'] ?? '';
    if ($csrfToken === '') {
        // For application/json bodies (e.g. delete via JSON), parse from input
        $contentType = $_SERVER['CONTENT_TYPE'] ?? '';
        if (strpos($contentType, 'application/json') !== false) {
            $body = json_decode(file_get_contents('php://input'), true) ?? [];
            $csrfToken = $body['csrf_token'] ?? '';
        }
    }
    if (!csrf_verify((string) $csrfToken)) {
        json_error('Invalid CSRF token', 403);
    }

    // Delete
    if (isset($_POST['action']) && $_POST['action'] === 'delete') {
        $fileId = intval($_POST['file_id'] ?? 0);
        if (!$fileId) json_error('file_id required');

        $file = load_file_row($fileId);
        if (!$file) json_error('File not found', 404);

        if (!user_can_access_entity((string) $file['entity_type'], (int) $file['entity_id'])) {
            json_error('File not found', 404);
        }

        // Delete from disk
        $path = $uploadDir . '/' . $file['file_path'];
        if (file_exists($path)) @unlink($path);

        db_query("DELETE FROM `{$prefix}file_uploads` WHERE id = ?", [$fileId]);
        audit_log('file', 'delete', $file['entity_type'], $file['entity_id'],
            "Deleted file '{$file['orig_name']}'");

        json_response(['success' => true]);
    }

    // Upload
    $entityType = $_POST['entity'] ?? '';
    $entityId = intval($_POST['entity_id'] ?? 0);
    $description = trim($_POST['description'] ?? '');

    $validEntities = ['incident', 'member', 'facility', 'equipment', 'vehicle', 'sop', 'general'];
    if (!in_array($entityType, $validEntities)) {
        json_error('Invalid entity type. Valid: ' . implode(', ', $validEntities));
    }

    if (!user_can_access_entity($entityType, $entityId)) {
        json_error('Insufficient permissions: cannot attach to this resource', 403);
    }

    if (empty($_FILES['file'])) {
        json_error('No file uploaded');
    }

    // Check disk space
    $stats = disk_usage_stats();
    $blockPct = (float) upload_config('upload_disk_block_pct', 80);
    if ($stats['disk_used_pct'] >= $blockPct) {
        json_error("Disk usage at {$stats['disk_used_pct']}% — uploads blocked (threshold: {$blockPct}%)", 507);
    }

    $maxMB = (float) upload_config('upload_max_file_size', 30);
    $maxBytes = $maxMB * 1048576;

    $file = $_FILES['file'];

    // Validate upload
    if ($file['error'] !== UPLOAD_ERR_OK) {
        $errors = [
            UPLOAD_ERR_INI_SIZE   => 'File exceeds PHP upload_max_filesize',
            UPLOAD_ERR_FORM_SIZE  => 'File exceeds form MAX_FILE_SIZE',
            UPLOAD_ERR_PARTIAL    => 'File was only partially uploaded',
            UPLOAD_ERR_NO_FILE    => 'No file was uploaded',
            UPLOAD_ERR_NO_TMP_DIR => 'Missing temp directory',
            UPLOAD_ERR_CANT_WRITE => 'Failed to write to disk',
        ];
        json_error($errors[$file['error']] ?? 'Upload error code ' . $file['error']);
    }

    if (!is_uploaded_file($file['tmp_name'])) {
        json_error('Invalid upload');
    }

    if ($file['size'] > $maxBytes) {
        json_error("File too large (" . round($file['size'] / 1048576, 1) . " MB). Maximum: {$maxMB} MB");
    }

    // ── HARDENED: derive MIME from the temp file, never trust $file['type']
    $detectedMime = null;
    if (function_exists('finfo_open')) {
        $finfo = @finfo_open(FILEINFO_MIME_TYPE);
        if ($finfo) {
            $detectedMime = @finfo_file($finfo, $file['tmp_name']);
            @finfo_close($finfo);
        }
    }
    if (!$detectedMime) {
        $detectedMime = @mime_content_type($file['tmp_name']) ?: '';
    }
    $detectedMime = strtolower(trim((string) $detectedMime));
    if ($detectedMime === '') {
        json_error('Could not determine file type — refusing upload');
    }

    // Derive canonical extension from MIME (allowlist enforcement)
    if (!isset($MIME_TO_EXT[$detectedMime])) {
        json_error("File type not allowed: {$detectedMime}");
    }
    $canonicalExt = $MIME_TO_EXT[$detectedMime];

    // Cross-check: the user-provided extension, if any, must agree with the
    // detected MIME — defends against polyglots that masquerade as legitimate
    // types but render differently.
    $userExt = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    if ($userExt !== '' && isset($ALLOWED_EXT_MIME[$userExt])) {
        if (!in_array($detectedMime, $ALLOWED_EXT_MIME[$userExt], true)) {
            json_error("File extension does not match content (.{$userExt} vs {$detectedMime})");
        }
    } elseif ($userExt !== '' && !isset($ALLOWED_EXT_MIME[$userExt])) {
        // User-supplied extension is on no allowlist — refuse rather than
        // silently rewriting it, so attackers can't smuggle "evil.php" up.
        json_error("File extension not allowed: .{$userExt}");
    }

    // Build target path
    $subDir = $entityType . '/' . $entityId;
    $targetDir = $uploadDir . '/' . $subDir;
    if (!is_dir($targetDir)) {
        @mkdir($targetDir, 0755, true);
    }

    // Generate safe filename — uses CANONICAL extension keyed off verified MIME.
    // The user-supplied extension is discarded entirely.
    $safeName = time() . '_' . bin2hex(random_bytes(4)) . '.' . $canonicalExt;
    $relPath = $subDir . '/' . $safeName;
    $absPath = $uploadDir . '/' . $relPath;

    if (!move_uploaded_file($file['tmp_name'], $absPath)) {
        json_error('Failed to save file to disk');
    }

    // Insert DB record
    $userId = (int) ($_SESSION['user_id'] ?? 0);
    $userName = $_SESSION['user'] ?? 'unknown';

    try {
        db_query(
            "INSERT INTO `{$prefix}file_uploads`
                (entity_type, entity_id, filename, orig_name, mime_type, file_size, file_path, uploaded_by, uploaded_by_name, description)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            [$entityType, $entityId, $safeName, $file['name'], $detectedMime, $file['size'], $relPath, $userId, $userName, $description]
        );
        $uploadId = db_insert_id();
    } catch (Exception $e) {
        @unlink($absPath); // Clean up on DB failure
        json_error('Database error: ' . $e->getMessage());
    }

    audit_log('file', 'upload', $entityType, $entityId,
        "Uploaded '{$file['name']}' (" . round($file['size'] / 1024) . " KB)");

    // Warn about disk space
    $warning = null;
    $warnPct = (float) upload_config('upload_disk_warn_pct', 70);
    $freshStats = disk_usage_stats();
    if ($freshStats['disk_used_pct'] >= $warnPct) {
        $warning = "Disk usage at {$freshStats['disk_used_pct']}% — approaching limit ({$blockPct}%)";
    }

    json_response([
        'success'  => true,
        'file_id'  => $uploadId,
        'filename' => $safeName,
        'orig_name' => $file['name'],
        'size'     => $file['size'],
        'mime'     => $detectedMime,
        'warning'  => $warning
    ]);
}

json_error('Method not allowed', 405);
